### ISSUE TITLE
python3: can't open file 'src/cyberdog_ros2/cyberdog_gazebo/script/launchsim.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by gigijoe** [MiRoboticsLab/cyberdog_sim#1]
I think this should be
python3 ./src/cyberdog_simulator/cyberdog_gazebo/script/launchsim.py

After running launchsim.py, the rviz2 doesn't works as expect and keeps showing the following message 

[rviz2-3] Warning: Invalid frame ID "vodom" passed to canTransform argument target_frame - frame does not exist
[rviz2-3]          at line 156 in /tmp/binarydeb/ros-galactic-tf2-0.17.5/src/buffer_core.cpp

**Comment by 562986047** [comment]
> I think this should be python3 ./src/cyberdog_simulator/cyberdog_gazebo/script/launchsim.py
> 
> After running launchsim.py, the rviz2 doesn't works as expect and keeps showing the following message
> 
> [rviz2-3] Warning: Invalid frame ID "vodom" passed to canTransform argument target_frame - frame does not exist [rviz2-3] at line 156 in /tmp/binarydeb/ros-galactic-tf2-0.17.5/src/buffer_core.cpp

Thank for your reminding! The wrong directory in Readme is corrected now.

The warning in rviz occured cause the rviz node didn't recieve the lcm from cyberdog_control program which would be converted to Ros2 topic /tf. Please check if your cyberdog_control program run correctly.
