### ISSUE TITLE
运行启动脚本后一段时间，Gazebo视窗中机器狗的四条腿消失，只剩躯干

### ISSUE THREAD

**Issue by Alkrick** [MiRoboticsLab/cyberdog_sim#3]
@kennithhow
 我按照https://miroboticslab.github.io/blogs/#/cn/cyberdog_gazebo_cn 以及https://github.com/MiRoboticsLab/cyberdog_sim 的文档说明在几台Ubuntu 20.04设备进行了基于ROS2 Galactic的仿真平台部署，希望在仿真环境下先测试CyberDog 2的调度和运动控制，但我们在编译时遇到一些问题，具体描述如下：
 
 
 首先，我们按文档说明安装了ros2_Galatic、Gazebo、LCM、Eigen、xacro，将cyberdog_sim.repos内仓库获取，在随后进行colcon build的时候，会遇到yaml-cpp版本不对（需要装yaml-cpp-0.6.3）、以及catkin_pkg、empy、lark、numpy等依赖不存在导致编译失败的情况（安装了相应的包后编译中与其相关的报错会被解决），也会遇到Eigen版本不对（按说明文档从https://github.com/eigenteam/eigen-git-mirror 获取的版本为3.3.9）导致在编译cyberdog_visual时有个与UnitX()有关的报错，从https://gitlab.com/libeigen/eigen 获取了最新版本的Eigen(目前3.4.90，2023年10月），会解决此问题。
 
 然后在编译cyberdog_gazebo时会出现lcmhandler相关的报错（见下面附件colcon_build_output_log.txt），但编译总体过程能完成，只提示有stderr输出。然后运行“python3 src/cyberdog_simulator/cyberdog_gazebo/script/launchsim.py”进行测试时，三个终端（cyberdog_control、cyberdog_gazebo和cyberdog_visual）均有提示有异常的输出如下附件。
 
 [colcon_build_output_log.txt](https://github.com/MiRoboticsLab/blogs/files/13166977/colcon_build_output_log.txt)
 [cyberdog_control_output.txt](https://github.com/MiRoboticsLab/blogs/files/13166963/cyberdog_control_output.txt)
 [cyberdog_gazebo_output.txt](https://github.com/MiRoboticsLab/blogs/files/13166964/cyberdog_gazebo_output.txt)
 [cyberdog_visual_output_1.txt](https://github.com/MiRoboticsLab/blogs/files/13166966/cyberdog_visual_output_1.txt)
 
 在什么都不做过了片刻之后，Gazebo视窗中的机器狗模型四条腿消失，只剩躯干，而在Rviz的窗口中其四肢则变为白色，左侧窗口的RobotModel字体变为红色，显示Status:Error（见附件RViz_error_screenshot.png）。此时，cyberdog_visual的输很多异常（见附件cyberdog_visual_output_2.txt）。

 ![RViz_error_screenshot](https://github.com/MiRoboticsLab/blogs/assets/103303486/53a348e3-8d70-4943-ad95-ec97cdc7db4c) [cyberdog_visual_output_2.txt](https://github.com/MiRoboticsLab/blogs/files/13167009/cyberdog_visual_output_2.txt)

 此问题数次尝试、在不同机子上能重复，请问该如何解决？ @northdk @ruheng @yangweiyou @zeroone001

**Comment by Alkrick** [comment]
参考文档：https://miroboticslab.github.io/blogs/#/cn/cyberdog_gazebo_cn
如果运行脚本之后gazebo正常启动及机器狗模型在悬空状态，问题可能是：
运行脚本gazebo启动比较慢，导致控制模块无法通信，可以按照参考文档的概述下的 “分别运行个程序” 章节依次运行程序。

如果gazebo正常启动及机器狗模型在爬下状态，问题可能是：
没有给发送控制指令，可以按照本参考文档的通信接口下的 “仿真例程” 章节运行键盘控制模块进行测试。

**Comment by kennithhow** [comment]
> 参考文档：https://miroboticslab.github.io/blogs/#/cn/cyberdog_gazebo_cn 如果运行脚本之后gazebo正常启动及机器狗模型在悬空状态，问题可能是： 运行脚本gazebo启动比较慢，导致控制模块无法通信，可以按照参考文档的概述下的 “分别运行个程序” 章节依次运行程序。
> 
> 如果gazebo正常启动及机器狗模型在爬下状态，问题可能是： 没有给发送控制指令，可以按照本参考文档的通信接口下的 “仿真例程” 章节运行键盘控制模块进行测试。



@Alkrick 你好，谢谢回复，我按照你说的分步加载模块进行了尝试，结果如下。
在没有运行仿真实例时：
1、如果顺序启动cyberdog_gazebo、cyberdog_control、cyberdog_visual三个模块，在不做任何操作不到一分钟，Gazebo视窗中机器狗四肢消失只剩躯干，cyberdog_visual视窗中RobotModel显示Status:Error。
2、如果顺序启动cyberdog_gazebo、cyberdog_control这两个模块，在不做任何操作不到几分钟，亦出现Gazebo视窗中机器狗四肢消失只剩躯干。
3、只启动cyberdog_gazebo模块，四肢不会消失，长时间后都不会有任何异常。值得一提的是，cyberdog_gazebo模块加载非常快，在Gazebo启动瞬间即可加载好模型正常显示，不像是它加载加慢造成的问题。

在有运动仿真实例时：
1、如果顺序启动cyberdog_gazebo、cyberdog_control、cyberdog_visual三个模块或只启动cyberdog_gazebo、cyberdog_control这两个模块，再快速在Gazebo视察中机器狗四肢消失前运行keybroad_commander并给出一个指令（如y，也即恢复站立模式），程序将正常运行，cyberdog_gazebo视窗中机器狗四肢不会消失，在cyberdog_visual视窗也不会显示状态异常，即便将keybroad_commander退出也能保持正常。但只要一开始未及时运行keybroad_commander，待机器狗四肢消失后再运行该程序时，四肢消失的器狗将不会有反应。
2、无论是顺序启动三个或两个模块，在运行cyberdogmsg_sender后会马上变成四肢消失的异常状态。甚至在只开cyberdog_gazebo模块然后先运行cyberdogmsg_sender，待其结束后再启动cyberdog_control模块，机器狗会瞬间变成四肢消失状态。而对只开cyberdog_gazebo然后直接运行keybroad_commander（由于没有加载运动控制模式，指令是不响应的），然后关闭keybroad_commander、运行cyberdog_control、再快速启动keybroad_commander，是可以正常运行程序的。

也即目前我应该可以在启动了cyberdog_gazebo和cyberdog_control模块后快速运行控制程序来应对四肢异常的状况。不过上面提到的其它异常不知原因为何，不知做其它操作时会否有影响，待测。

**Comment by Alkrick** [comment]
> @Alkrick 你好，谢谢回复，我按照你说的分步加载模块进行了尝试，结果如下。 在没有运行仿真实例时： 1、如果顺序启动cyberdog_gazebo、cyberdog_control、cyberdog_visual三个模块，在不做任何操作不到一分钟，Gazebo视窗中机器狗四肢消失只剩躯干，cyberdog_visual视窗中RobotModel显示Status:Error。 2、如果顺序启动cyberdog_gazebo、cyberdog_control这两个模块，在不做任何操作不到几分钟，亦出现Gazebo视窗中机器狗四肢消失只剩躯干。 3、只启动cyberdog_gazebo模块，四肢不会消失，长时间后都不会有任何异常。值得一提的是，cyberdog_gazebo模块加载非常快，在Gazebo启动瞬间即可加载好模型正常显示，不像是它加载加慢造成的问题。
> 
> 在有运动仿真实例时： 1、如果顺序启动cyberdog_gazebo、cyberdog_control、cyberdog_visual三个模块或只启动cyberdog_gazebo、cyberdog_control这两个模块，再快速在Gazebo视察中机器狗四肢消失前运行keybroad_commander并给出一个指令（如y，也即恢复站立模式），程序将正常运行，cyberdog_gazebo视窗中机器狗四肢不会消失，在cyberdog_visual视窗也不会显示状态异常，即便将keybroad_commander退出也能保持正常。但只要一开始未及时运行keybroad_commander，待机器狗四肢消失后再运行该程序时，四肢消失的器狗将不会有反应。 2、无论是顺序启动三个或两个模块，在运行cyberdogmsg_sender后会马上变成四肢消失的异常状态。甚至在只开cyberdog_gazebo模块然后先运行cyberdogmsg_sender，待其结束后再启动cyberdog_control模块，机器狗会瞬间变成四肢消失状态。而对只开cyberdog_gazebo然后直接运行keybroad_commander（由于没有加载运动控制模式，指令是不响应的），然后关闭keybroad_commander、运行cyberdog_control、再快速启动keybroad_commander，是可以正常运行程序的。
> 
> 也即目前我应该可以在启动了cyberdog_gazebo和cyberdog_control模块后快速运行控制程序来应对四肢异常的状况。不过上面提到的其它异常不知原因为何，不知做其它操作时会否有影响，待测。


@kennithhow 感谢你细致的回复，你可以暂时用快速运行控制程序应对四肢异常状态，我们会继续寻找异常原因，尽快解决。目前本issue将保持为未解决状态，你可以关注一下后面的更新。

**Comment by 562986047** [comment]
> @kennithhow 我按照https://miroboticslab.github.io/blogs/#/cn/cyberdog_gazebo_cn 以及https://github.com/MiRoboticsLab/cyberdog_sim 的文档说明在几台Ubuntu 20.04设备进行了基于ROS2 Galactic的仿真平台部署，希望在仿真环境下先测试CyberDog 2的调度和运动控制，但我们在编译时遇到一些问题，具体描述如下：
> 
> 首先，我们按文档说明安装了ros2_Galatic、Gazebo、LCM、Eigen、xacro，将cyberdog_sim.repos内仓库获取，在随后进行colcon build的时候，会遇到yaml-cpp版本不对（需要装yaml-cpp-0.6.3）、以及catkin_pkg、empy、lark、numpy等依赖不存在导致编译失败的情况（安装了相应的包后编译中与其相关的报错会被解决），也会遇到Eigen版本不对（按说明文档从https://github.com/eigenteam/eigen-git-mirror 获取的版本为3.3.9）导致在编译cyberdog_visual时有个与UnitX()有关的报错，从https://gitlab.com/libeigen/eigen 获取了最新版本的Eigen(目前3.4.90，2023年10月），会解决此问题。
> 
> 然后在编译cyberdog_gazebo时会出现lcmhandler相关的报错（见下面附件colcon_build_output_log.txt），但编译总体过程能完成，只提示有stderr输出。然后运行“python3 src/cyberdog_simulator/cyberdog_gazebo/script/launchsim.py”进行测试时，三个终端（cyberdog_control、cyberdog_gazebo和cyberdog_visual）均有提示有异常的输出如下附件。
> 
> [colcon_build_output_log.txt](https://github.com/MiRoboticsLab/blogs/files/13166977/colcon_build_output_log.txt) [cyberdog_control_output.txt](https://github.com/MiRoboticsLab/blogs/files/13166963/cyberdog_control_output.txt) [cyberdog_gazebo_output.txt](https://github.com/MiRoboticsLab/blogs/files/13166964/cyberdog_gazebo_output.txt) [cyberdog_visual_output_1.txt](https://github.com/MiRoboticsLab/blogs/files/13166966/cyberdog_visual_output_1.txt)
> 
> 在什么都不做过了片刻之后，Gazebo视窗中的机器狗模型四条腿消失，只剩躯干，而在Rviz的窗口中其四肢则变为白色，左侧窗口的RobotModel字体变为红色，显示Status:Error（见附件RViz_error_screenshot.png）。此时，cyberdog_visual的输很多异常（见附件cyberdog_visual_output_2.txt）。
> 
> ![RViz_error_screenshot](https://user-images.githubusercontent.com/103303486/278040142-53a348e3-8d70-4943-ad95-ec97cdc7db4c.png) [cyberdog_visual_output_2.txt](https://github.com/MiRoboticsLab/blogs/files/13167009/cyberdog_visual_output_2.txt)
> 
> 此问题数次尝试、在不同机子上能重复，请问该如何解决？ @northdk @ruheng @yangweiyou @zeroone001

@Alkrick 你好，该问题的根因是在在于当机器人在趴下的初始状态时，仿真器中的与地面接触点过多导致的求解器异常。可以通过将gazebo ode的求解器从world更改为quick。quick求解器的精度相比world略低，但其求解方法能够保证在多点接触时不出现异常。
具体的更改方法为将cyberdog_simulator/cyberdog_gazebo/world/simple.world中ode的type改为quick，如下所示
```
<physics type="ode">
            <max_step_size>0.001</max_step_size>
            <real_time_factor>1</real_time_factor>
            <real_time_update_rate>1000</real_time_update_rate>
            <gravity>0 0 -9.81</gravity>
            <ode>
                <solver>
                <type>quick</type>
                <min_step_size>0.0001</min_step_size>   
                <iters>50</iters> 
                <sor>1.3</sor>
                </solver>  
                <constraints>
                <cfm>0.0</cfm>
                <erp>0.2</erp>
                </constraints>  
            </ode>
        </physics>

```

**Comment by kennithhow** [comment]
> > @kennithhow 我按照https://miroboticslab.github.io/blogs/#/cn/cyberdog_gazebo_cn 以及https://github.com/MiRoboticsLab/cyberdog_sim 的文档说明在几台Ubuntu 20.04设备进行了基于ROS2 Galactic的仿真平台部署，希望在仿真环境下先测试CyberDog 2的调度和运动控制，但我们在编译时遇到一些问题，具体描述如下：
> > 首先，我们按文档说明安装了ros2_Galatic、Gazebo、LCM、Eigen、xacro，将cyberdog_sim.repos内仓库获取，在随后进行colcon build的时候，会遇到yaml-cpp版本不对（需要装yaml-cpp-0.6.3）、以及catkin_pkg、empy、lark、numpy等依赖不存在导致编译失败的情况（安装了相应的包后编译中与其相关的报错会被解决），也会遇到Eigen版本不对（按说明文档从https://github.com/eigenteam/eigen-git-mirror 获取的版本为3.3.9）导致在编译cyberdog_visual时有个与UnitX()有关的报错，从https://gitlab.com/libeigen/eigen 获取了最新版本的Eigen(目前3.4.90，2023年10月），会解决此问题。
> > 然后在编译cyberdog_gazebo时会出现lcmhandler相关的报错（见下面附件colcon_build_output_log.txt），但编译总体过程能完成，只提示有stderr输出。然后运行“python3 src/cyberdog_simulator/cyberdog_gazebo/script/launchsim.py”进行测试时，三个终端（cyberdog_control、cyberdog_gazebo和cyberdog_visual）均有提示有异常的输出如下附件。
> > [colcon_build_output_log.txt](https://github.com/MiRoboticsLab/blogs/files/13166977/colcon_build_output_log.txt) [cyberdog_control_output.txt](https://github.com/MiRoboticsLab/blogs/files/13166963/cyberdog_control_output.txt) [cyberdog_gazebo_output.txt](https://github.com/MiRoboticsLab/blogs/files/13166964/cyberdog_gazebo_output.txt) [cyberdog_visual_output_1.txt](https://github.com/MiRoboticsLab/blogs/files/13166966/cyberdog_visual_output_1.txt)
> > 在什么都不做过了片刻之后，Gazebo视窗中的机器狗模型四条腿消失，只剩躯干，而在Rviz的窗口中其四肢则变为白色，左侧窗口的RobotModel字体变为红色，显示Status:Error（见附件RViz_error_screenshot.png）。此时，cyberdog_visual的输很多异常（见附件cyberdog_visual_output_2.txt）。
> > ![RViz_error_screenshot](https://user-images.githubusercontent.com/103303486/278040142-53a348e3-8d70-4943-ad95-ec97cdc7db4c.png) [cyberdog_visual_output_2.txt](https://github.com/MiRoboticsLab/blogs/files/13167009/cyberdog_visual_output_2.txt)
> > 此问题数次尝试、在不同机子上能重复，请问该如何解决？ @northdk @ruheng @yangweiyou @zeroone001
> 
> @Alkrick 你好，该问题的根因是在在于当机器人在趴下的初始状态时，仿真器中的与地面接触点过多导致的求解器异常。可以通过将gazebo ode的求解器从world更改为quick。quick求解器的精度相比world略低，但其求解方法能够保证在多点接触时不出现异常。 具体的更改方法为将cyberdog_simulator/cyberdog_gazebo/world/simple.world中ode的type改为quick，如下所示
> 
> ```
> <physics type="ode">
>             <max_step_size>0.001</max_step_size>
>             <real_time_factor>1</real_time_factor>
>             <real_time_update_rate>1000</real_time_update_rate>
>             <gravity>0 0 -9.81</gravity>
>             <ode>
>                 <solver>
>                 <type>quick</type>
>                 <min_step_size>0.0001</min_step_size>   
>                 <iters>50</iters> 
>                 <sor>1.3</sor>
>                 </solver>  
>                 <constraints>
>                 <cfm>0.0</cfm>
>                 <erp>0.2</erp>
>                 </constraints>  
>             </ode>
>         </physics>
> ```

@562986047 @Alkrick 你们好！我将Gazebo ODE求解器由world改为quick后问题解决了，即使直接运行launchsim.py也没有出现机器狗四肢消失的问题。谢谢帮助！
不过在运行cyberdogmsg_sender后依然会出现异常，机器狗会先从趴下状态起立，然后马上四肢消失，Rviz显示Status:Error，同时cyberdog_control终端反复输出：
```
...
[RecoveryStand] SaftyCheck Warning lasting for 1.0s at Motor11!
[RecoveryStand] Fold legs
[RecoveryStand] SaftyCheck Warning lasting for 1.0s at Motor11!
[RecoveryStand] Fold legs
[CONTROL FSM] Operating Mode: NORMAL in recovery_stand

[RecoveryStand] SaftyCheck Warning lasting for 1.0s at Motor11!
[RecoveryStand] Fold legs
...
```

**Comment by 562986047** [comment]
> > > @kennithhow 我按照https://miroboticslab.github.io/blogs/#/cn/cyberdog_gazebo_cn 以及https://github.com/MiRoboticsLab/cyberdog_sim 的文档说明在几台Ubuntu 20.04设备进行了基于ROS2 Galactic的仿真平台部署，希望在仿真环境下先测试CyberDog 2的调度和运动控制，但我们在编译时遇到一些问题，具体描述如下：
> > > 首先，我们按文档说明安装了ros2_Galatic、Gazebo、LCM、Eigen、xacro，将cyberdog_sim.repos内仓库获取，在随后进行colcon build的时候，会遇到yaml-cpp版本不对（需要装yaml-cpp-0.6.3）、以及catkin_pkg、empy、lark、numpy等依赖不存在导致编译失败的情况（安装了相应的包后编译中与其相关的报错会被解决），也会遇到Eigen版本不对（按说明文档从https://github.com/eigenteam/eigen-git-mirror 获取的版本为3.3.9）导致在编译cyberdog_visual时有个与UnitX()有关的报错，从https://gitlab.com/libeigen/eigen 获取了最新版本的Eigen(目前3.4.90，2023年10月），会解决此问题。
> > > 然后在编译cyberdog_gazebo时会出现lcmhandler相关的报错（见下面附件colcon_build_output_log.txt），但编译总体过程能完成，只提示有stderr输出。然后运行“python3 src/cyberdog_simulator/cyberdog_gazebo/script/launchsim.py”进行测试时，三个终端（cyberdog_control、cyberdog_gazebo和cyberdog_visual）均有提示有异常的输出如下附件。
> > > [colcon_build_output_log.txt](https://github.com/MiRoboticsLab/blogs/files/13166977/colcon_build_output_log.txt) [cyberdog_control_output.txt](https://github.com/MiRoboticsLab/blogs/files/13166963/cyberdog_control_output.txt) [cyberdog_gazebo_output.txt](https://github.com/MiRoboticsLab/blogs/files/13166964/cyberdog_gazebo_output.txt) [cyberdog_visual_output_1.txt](https://github.com/MiRoboticsLab/blogs/files/13166966/cyberdog_visual_output_1.txt)
> > > 在什么都不做过了片刻之后，Gazebo视窗中的机器狗模型四条腿消失，只剩躯干，而在Rviz的窗口中其四肢则变为白色，左侧窗口的RobotModel字体变为红色，显示Status:Error（见附件RViz_error_screenshot.png）。此时，cyberdog_visual的输很多异常（见附件cyberdog_visual_output_2.txt）。
> > > ![RViz_error_screenshot](https://user-images.githubusercontent.com/103303486/278040142-53a348e3-8d70-4943-ad95-ec97cdc7db4c.png) [cyberdog_visual_output_2.txt](https://github.com/MiRoboticsLab/blogs/files/13167009/cyberdog_visual_output_2.txt)
> > > 此问题数次尝试、在不同机子上能重复，请问该如何解决？ @northdk @ruheng @yangweiyou @zeroone001
> > 
> > 
> > @Alkrick 你好，该问题的根因是在在于当机器人在趴下的初始状态时，仿真器中的与地面接触点过多导致的求解器异常。可以通过将gazebo ode的求解器从world更改为quick。quick求解器的精度相比world略低，但其求解方法能够保证在多点接触时不出现异常。 具体的更改方法为将cyberdog_simulator/cyberdog_gazebo/world/simple.world中ode的type改为quick，如下所示
> > ```
> > <physics type="ode">
> >             <max_step_size>0.001</max_step_size>
> >             <real_time_factor>1</real_time_factor>
> >             <real_time_update_rate>1000</real_time_update_rate>
> >             <gravity>0 0 -9.81</gravity>
> >             <ode>
> >                 <solver>
> >                 <type>quick</type>
> >                 <min_step_size>0.0001</min_step_size>   
> >                 <iters>50</iters> 
> >                 <sor>1.3</sor>
> >                 </solver>  
> >                 <constraints>
> >                 <cfm>0.0</cfm>
> >                 <erp>0.2</erp>
> >                 </constraints>  
> >             </ode>
> >         </physics>
> > ```
> 
> @562986047 @Alkrick 你们好！我将Gazebo ODE求解器由world改为quick后问题解决了，即使直接运行launchsim.py也没有出现机器狗四肢消失的问题。谢谢帮助！ 不过在运行cyberdogmsg_sender后依然会出现异常，机器狗会先从趴下状态起立，然后马上四肢消失，Rviz显示Status:Error，同时cyberdog_control终端反复输出：
> 
> ```
> ...
> [RecoveryStand] SaftyCheck Warning lasting for 1.0s at Motor11!
> [RecoveryStand] Fold legs
> [RecoveryStand] SaftyCheck Warning lasting for 1.0s at Motor11!
> [RecoveryStand] Fold legs
> [CONTROL FSM] Operating Mode: NORMAL in recovery_stand
> 
> [RecoveryStand] SaftyCheck Warning lasting for 1.0s at Motor11!
> [RecoveryStand] Fold legs
> ...
> ```

@kennithhow 你好！我们尝试复现该问题，发现只有部分的电脑会出现该问题。该问题原因是由于cyberdogmsg_sender中apply_force的功能引起的，可以尝试将cyberdog_example/src/cyberdogmsg_sender.cpp中该部分代码注释掉，再运行试试。
注释以下代码：
```
//apply force on FrontLeft leg
    std::array<double, 3> rel_pos_;
    std::array<double, 3> force_;
    force_[2] = 20;

    force_message_.link_name = "FL_knee";
    force_message_.rel_pos = rel_pos_;
    force_message_.force = force_;
    force_message_.time = 2;
    force_pub_->publish(force_message_);
    std::cout<<"applying force on FL_knee ..."<<std::endl;
```
目前认为该问题是由于环境不同导致gazebo AddForceAtRelativePosition()函数出现错误，但问题的根因暂时未知，待后续分析解决。

**Comment by kennithhow** [comment]
@562986047 你好，我将“apply force on FrontLeft leg”代码注释掉后不再出现机器狗四肢消失异常，那在问题解决前我将避免在force_message_通信，谢谢帮助！

**Comment by YuRuiii** [comment]
@Alkrick 你好！我在执行colcon build前，按照README的要求把`src/cyberdog_locomotion/CMakeLists.txt`中的BUILD_ROS置为了ON，在执行colcon build到编译cyberdog_locomotion时也遇到了和您[colcon_build_output_log.txt](https://github.com/MiRoboticsLab/blogs/files/13166977/colcon_build_output_log.txt)文件相同的报错。具体地，我的colcon build output log是
```
[5.372s] WARNING:colcon.colcon_ros.prefix_path.ament:The path '/home/gcx/yr/cyberdog_sim/install' in the environment variable AMENT_PREFIX_PATH doesn't contain any 'local_setup.*' files.
Starting >>> cyberdog_msg
Starting >>> cyberdog_description          
Starting >>> cyberdog_visual                                                         
Starting >>> cyberdog_locomotion                                                                              
Finished <<< cyberdog_visual [2.48s]                                                                              
Finished <<< cyberdog_description [3.59s]                                                                
Finished <<< cyberdog_msg [4.37s]                                                                     
Starting >>> cyberdog_example
Starting >>> cyberdog_gazebo                                                                      
Finished <<< cyberdog_example [2.27s]                                                                             
Finished <<< cyberdog_gazebo [2.37s]                                                                      
Starting >>> cyberdog_simulator
Finished <<< cyberdog_simulator [1.85s]                                                                      
[Processing: cyberdog_locomotion]                             
[Processing: cyberdog_locomotion]                                      
[Processing: cyberdog_locomotion]                                       
[Processing: cyberdog_locomotion]                                       
[Processing: cyberdog_locomotion]                                       
[Processing: cyberdog_locomotion]                                       
[Processing: cyberdog_locomotion]                                       
[Processing: cyberdog_locomotion]                                       
--- stderr: cyberdog_locomotion                                          
**** Onboard Build disabled ****
---
Finished <<< cyberdog_locomotion [4min 26s]

Summary: 7 packages finished [4min 32s]
  1 package had stderr output: cyberdog_locomotion
```
和你的log一样，我也遇到了`**** Onboard Build disabled ****`的输出。

当我将`src/cyberdog_locomotion/CMakeLists.txt`中的`ONBOARD_BUILD`也置为ON后，也会出现这个问题。

因此，我的`install/share/cyberdog_locomotion`中没有`cmake`等文件夹，我猜测这也是我后续运行时出问题的原因。
<img width="292" alt="Screenshot 2023-11-19 at 23 31 48" src="https://github.com/MiRoboticsLab/cyberdog_sim/assets/88995309/e51a5b4c-5422-4cf6-bba4-050f92669f97">


请问您现在编译时还会出现这样的问题吗？

谢谢！

**Comment by YuRuiii** [comment]
我已经解决以上的问题。问题的原因是我不太熟悉CMakeLists.txt的编程，我之前的操作是：

```
option(BUILD_ROS "Build cyber dog for ROS2" ON)
```

我以为这样就可以设置BUILD_ROS为ON。但我通过

```
message("BUILD_ROS is set to: ${BUILD_ROS}")
```

发现BUILD_ROS还是OFF。

我最后通过
```
set(BUILD_ROS ON)
```

把BUILD_ROS设置为ON，这次可以成功运行。感谢你的帮助！

**Comment by yeguo04** [comment]
运行cyberdog_control_launch.py文件时，为何一直出现以下问题：[ERROR] SharedMemoryObject::Attach shm_open(development-simulator) failed: No such file or directory
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to create shared memory!
Aborted (core dumped)
请问该如何解决呢？是什么原因造成的呢
