### ISSUE TITLE
设置fixed frame 为vodom时rviz2无法收到雷达数据

### ISSUE THREAD

**Issue by yjrqz777** [MiRoboticsLab/cyberdog_sim#5]
设置fixed frame 为vodom时rviz2无法收到雷达数据,设置为head时可以收到雷达数据并显示，但是控制狗运动的时候是地图在运动，不是狗在地图上移动

**Comment by 562986047** [comment]
> 设置fixed frame 为vodom时rviz2无法收到雷达数据,设置为head时可以收到雷达数据并显示，但是控制狗运动的时候是地图在运动，不是狗在地图上移动

这是因为之前版本的rviz2 launch程序中的use_sim_time没有被正确赋值，导致rivz2的时间戳与gazebo发出的不一致从而无法处理topic数据，该问题已在cyberdog_simulator仓的main分支进行修复

**Comment by yjrqz777** [comment]
> > 设置fixed frame 为vodom时rviz2无法收到雷达数据,设置为head时可以收到雷达数据并显示，但是控制狗运动的时候是地图在运动，不是狗在地图上移动
> 
> 这是因为之前版本的rviz2 launch程序中的use_sim_time没有被正确赋值，导致rivz2的时间戳与gazebo发出的不一致从而无法处理topic数据，该问题已在cyberdog_simulator仓的main分支进行修复

感谢，请问仿真使用的protobuf具体版本是多少

**Comment by 562986047** [comment]
仿真中使用的protobuf是gazebo环境自带的， 目前该环境下的版本是3.15.8
